before_script:
  - docker info

build_image:
  script:
    - docker build -t 10.64.0.50:5000/lzh/neutron-plugin-openvswitch-agent:kilo .
    - docker push 10.64.0.50:5000/lzh/neutron-plugin-openvswitch-agent:kilo
